[package]
name = "cargo-checkout"
version = "0.1.0"
description = "Maintain separate working directories for your repo."
authors = ["Kevin M Granger <git@kevinmgranger.me>"]
license = "MPL-2.0"
readme = "README.md"
edition = "2018"

[badges.maintenance]
status = "experimental"

[dependencies]
git2 = "0.8.0"
structopt = "0.2.14"
failure = "0.1.5"
rayon = "1.0.3"