[package]
name = "cargo-checkout"
version = "0.1.0"
description = "Easily maintain separate working directories, for decoupled testing or other uses."
authors = ["Kevin M Granger <git@kevinmgranger.me>"]
license = "MPL-2.0"
readme = "README.md"
edition = "2018"

[badges.maintenance]
status = "experimental"

[dependencies]
git2 = "0.8.0"
tempdir = "0.3.7"